.na
.TH SNEBU-CLIENT "1" "December 2020" "snebu-client" "User Commands"
.SH NAME
snebu-client \- manual page for snebu-client
.SH SYNOPSIS
.B snebu-client
[ \fI\,subcommand \/\fR] [ \fI\,options \/\fR]
.SH DESCRIPTION
snebu\-client is the client front end for snebu.
Use it to easily
back up a local or remote host, to either local a local storage
device, or to a remote backup server.  Use it with one of the
following subcommands.
.SS "Sub commands are as follows:"
.PP
\fBbackup\fR
[ \fB\-n\fR backupname ] [ \fB\-d\fR datestamp ] [ \fB\-r\fR schedule ]
.RS 4
Initiates a backup.
.RE
.PP
\fBrestore\fR
[ \fB\-n\fR backupname ] [ \fB\-d\fR datestamp ]
.RS 4
Initates a restore.
.RE
.PP
\fBlistbackups\fR [ \fB\-n\fR backupname [ \fB\-d\fR datestamp ]] [ file_list... ]
.RS 4
List backed up hosts, backupsets within a host, or files within a backupset.
.RE
.PP
\fBvalidate\fR \fB\-n\fR backupname \fB\-d\fR datestamp
.RS 4
Validates a given backup.
.RE
.PP
\fBhelp\fR [subcommand]
.RS 4
Displays help page of subcommand
.RE
.SH "SEE ALSO"
.hy 0
\fBsnebu\-client\-backup\fR(1),
\fBsnebu\-client\-restore\fR(1),
\fBsnebu\-client\-listbackups\fR(1),
\fBsnebu\-client\-validate\fR(1),
.PP
.RE
