.na
.TH SNEBU-CLIENT-BACKUP "1" "December 2020" "snebu-client backup" "User Commands"
.SH NAME
snebu-client backup \- Initiates a backup
.SH SYNOPSIS
.B snebu-client
\fB\,backup \/\fR
[ \fB-n\fR \fIbackupname\fR ]
[ \fB-d\fR \fIdatestamp\fR ]
[ \fB-r\fR \fIschedule\fR ]
[ \fIfile\-list\fR ]
.SH DESCRIPTION
Initiates a system backup.
By default, it will back up the local host to a local snebu install.
You can also use this command to back up to a remote backup server,
back up a remote host to either a local snebu instalation,
or back up a remote host to another remote backup server,
depending on which options are chosen.
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-config\fR \fIconfig_file\fR
Name of the configuration file.  Default is
\fI\,/etc/snebu\-client.conf\/\fP.
.TP
\fB\-n\fR, \fB\-\-name\fR \fIbackupname\fR
Name of the backup.  Usually set to the server
name that you are backing up.
.TP
\fB\-d\fR, \fB\-\-date\fR \fIdatestamp\fR
Date stamp for this backup set.  The format is in
time_t format, sames as the output of the "date\~+%s" command.
.TP
\fB\-r\fR, \fB\-\-retention\fR \fIschedule\fR
Retention schedule for this backup set.  Typical
values are "daily", "weekly", "monthly", "yearly".
.TP
\fB\-k\fR, \fB\-\-encryption\-key\fR \fIkeyfile\fR
Turns on encryption, and specifies encryption
key location.  May be specified more than once to
encrypt with multiple keys.
.IP
The program "tarcrypt" needs to be present on the
client for this option.  Keys are generated with
the command:
.IP
\fBtarcrypt genkey \-f\fR \fIkeyfile\fR [ \fB-c\fR \fIcomment\fR ]
.TP
\fB\-C\fR, \fB\-\-changedir\fR \fIpath\fR
Changes to the given directory path before backing up.
.TP
\fB\-\-graft\fR \fI/path/name/\fR\fB=\fR\fI/new/name/\fR
Re\-write path names beginning with "\fI/path/name/\fR"
to "\fI/new/name/\fR"
.TP
\fB\-f\fR, \fB\-\-force\-full\fR
Force a full backup
.TP
\fB\-\-remote\-client\fR \fIhostname\fR
Host name / IP address of remote host.  Used to
backup a remote host to local backup server.
.TP
\fB\-\-remote\-user\fR \fIuserid\fR
User ID for remote remote\-client.  Defaults to
root.
.TP
\fB\-\-sudo\fR \fIuserid\fR
Initial login User ID for remote remote\-client.
This ID uses sudo to switch to remote\-user once
logged in.
.TP
\fB\-\-backup\-server\fR \fIhostname\fR
Host name / IP address of backup server.  Used to
backup to a remote server.
.TP
\fB\-\-backup\-user\fR \fIuserid\fR
User ID for remote backup\-server.
.TP
\fB\-\-plugin\fR \fIscriptname\fR
Specifies an optional plug in script.  Usually
used to perform database\-specific operations
(such as enabling hot backup mode) for systems
with a DB installed.
.TP
[ \fIfile\-list\fR ]
List of files to backup.
Overrides default specified in snebu-client.conf file.
.SH "SEE ALSO"
\fBtarcrypt\fR(1)
