.TH SNEBU-CLIENT-RESTORE "1" "December 2020" "snebu-client-restore" "User Commands"
.na
.SH NAME
snebu-client restore \- Restores a backup
.SH SYNOPSIS
.B snebu-client
\fBrestore\fR
[ \fB-n\fR \fIbackupname\fR ]
[ \fB-d\fR \fIdatestamp\fR ]
[ \fIfile-list\fR ]
.SH DESCRIPTION
Restores a given backup session identified by "\-n" and "\-d"
parameters.  Use the "listbackups" subcommand to get a list of
available backup sessions.
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-config\fR \fIconfig_file\fR
Name of the configuration file.  Default is
\fI/etc/snebu\-client.conf\/\fP.
.TP
\fB\-n\fR, \fB\-\-name\fR \fIbackupname\fR
Name of the backup.  Usually set to the server
name that you are backing up.
.TP
\fB\-d\fR, \fB\-\-date\fR \fIdatestamp\fR
Date stamp for this backup set.  The format is in
time_t format, sames as the output of the "date
+%s" command.
.TP
\fB\-\-decrypt\fR
Turns on decryption.  Requires "tarcrypt" to be
on the client.  Password(s) will be prompted for
during restore.
.TP
\fB\-C\fR, \fB\-\-changedir\fR \fIpath\fR
Changes to the given directory path before restoring.
.TP
\fB\-\-graft\fR \fI/path/name/\fR\fB=\fR\fI/new/name/\fR
Re\-write path names beginning with "\fI/path/name/\fR"
to "\fI/new/name/\fR"
.TP
\fB\-\-remote\-client\fR \fIhostname\fR
Host name / IP address of remote host.  Used to
backup a remote host to local backup server.
.TP
\fB\-\-remote\-user\fR \fIuserid\fR
User ID for remote remote\-client.
Defaults to root.
.TP
\fB\-\-sudo\fR \fIuserid\fR
Initial login User ID for remote remote\-client.
This ID uses sudo to switch to remote\-user once
logged in.
.TP
\fB\-\-backup\-server\fR \fIhostname\fR
Host name / IP address of backup server.  Used to
backup to a remote server.
.TP
\fB\-\-backup\-user\fR \fIuserid\fR
User ID for remote backup\-server.
.TP
[ \fIfile\-list\fR ]
List of files to restore.  Defaults to all.
.SH "SEE ALSO"
\fBtarcrypt\fR(1)
.PP
