.TH SNEBU-CLIENT "1" "December 2020" "snebu-client" "User Commands"
.na
.SH NAME
snebu-client \- Front-end client for the snebu backup system
.SH SYNOPSIS
.B snebu-client
[ \fIsubcommand \/\fR] [ \fIoptions \/\fR]
.SH DESCRIPTION
snebu\-client is the client front end for snebu.
Use it to easily
back up a local or remote host, to either local a local storage
device, or to a remote backup server.  Use it with one of the
following subcommands.
.SS "Sub commands are as follows:"
.TP
\fBbackup\fR [ \fB\-n\fR \fIbackupname\fR ] [ \fB\-d\fR \fIdatestamp\fR ] [ \fB\-r\fR \fIschedule\fR ]
Initiates a backup.
.TP
\fBrestore\fR [ \fB\-n\fR \fIbackupname\fR ] [ \fB\-d\fR \fIdatestamp\fR ]
Initiates a restore.
.TP
\fBlistbackups\fR [ \fB\-n\fR \fIbackupname\fR [ \fB\-d\fR \fIdatestamp\fR ]] [ \fIfile_list\fR... ]
List backed up hosts, backup sets within a host, or files within a backup set.
.TP
\fBvalidate\fR \fB\-n\fR \fIbackupname\fR \fB\-d\fR \fIdatestamp\fR
Validates a given backup.
.TP
\fBhelp\fR [ \fIsubcommand\fR ]
Displays help page of subcommand
.RE
.SH "SEE ALSO"
.hy 0
\fBsnebu\-client\-backup\fR(1),
\fBsnebu\-client\-restore\fR(1),
\fBsnebu\-client\-listbackups\fR(1),
\fBsnebu\-client\-validate\fR(1),
.PP
.RE
