.na
.TH SNEBU-CLIENT-LISTBACKUPS "1" "December 2020" "snebu-client listbackups" "User Commands"
.SH NAME
snebu-client listbackups \- Lists backed up systems, backup sets, and file names
.SH SYNOPSIS
.B snebu-client
\fB\,listbackups\fR
[ \fB-n\fR \fIhostname\fR [ \fB-d\fR \fIdatestamp\fR ]]
[ \fIfile_list\fR... ]
.SH DESCRIPTION
With no arguments specified, "listbackups" will return a list of all
systems that are contained in the backup catalog.  Otherwise, when
specifying the \fB\-n\fR parameter, a list of backup sets for that host is
returned.
.SH OPTIONS
.TP
\fB\-c\fR, \fB\-\-config\fR \fIconfig_file\fR
Name of the configuration file.
Default is \fI\,/etc/snebu\-client.conf\/\fP.
.TP
\fB\-n\fR, \fB\-\-name\fR \fIbackupname\fR
Name of the backup.
Usually set to the server name that you are backing up.
.TP
\fB\-d\fR, \fB\-\-date\fR \fIdatestamp\fR
Date stamp for this backup set.
The format is in \fItime_t\fR format,
sames as the output of the "date\~+%s" command.
.TP
[ \fIfile\-list\fR ]
List of files to restore.  Defaults to all.
