== Quick start

=== Compiling / Installation

 tar -zxvf snebu-1.1.0.tar.gz
 make
 sudo make install

Then to set up privilege separation:

 sudo useradd -r -U -d /var/lib/snebu snebu
 sudo chown snebu:snebu 

This creates a user and group called "snebu", installing the snebu binary as SUID to user "snebu".  The config file /etc/sneub.conf defaults to placing the vault in `/var/lib/snebu/vault` and the backup catalog DB in `/var/lib/snebu/catalog`.  The `vault` directory is where the backed up files are stored, and the `catalog` directory holds the backup catalog database (in SQLite format).

You can mount an external storage device on /var/lib/snebu (making sure the `snebu` user/group owns the directory after mounting -- if not, `chown snebu:snebu /var/lib/snebu/` once the drive is mounted).  However, if the storage device has slow seek times, which is the case with many 2.5" USB-powered mechanical hard drives, then you will get better performance by mounting the mechanical drive under `/var/lib/snebu/vault`, and mounting a separate SSD drive in `/var/lib/snebu/catalog` (or the appropriate directories specified in `/etc/snebu.conf`.  Or if you keep the `catalog` directory on the local systems drive then be sure to separately copy the contents of the catalog directory to the external storage device after a backup session finishes.

=== Sample Backup and Restore Operation

==== User and permissions setup
You will need to set up user permissions for any user ID that access the `snebu` binary.  To set up permissions for the `root` user, run the following commands:

----
$ sudo -u snebu snebu permissions --add --command '*' --name '*' --user root
----

If a user other than root needs to run snebu, then they need to be added to the snebu group.

==== Run a backup
`sudo` is needed here to allow snebu-client to read all the files on the host.  If a user is only backing up their own directory then sudo isn't needed, and they can be given more granular permissions to the `snebu` command -- see the man page snebu-permissions(1).
----
$ sudo snebu-client backup
----

This backs up all mounted disk-based file systems (automatically skips tmpfs, procfs, sysfs, and other "nodev" mount points).  The backup name defaults to the host name of the client, however this can be overridden with `--name` parameter.  You can also follow the command with a file or path list.  For example:

----
$ sudo snebu-client backup -n boss-home-dir /home/bigboss
----

==== List backups, contents, and restore a file
----
$ sudo snebu-client listbackups -v

bosshost1
    1608761077 / daily / Wed Dec 23 16:04:37 2020
----
----
$ sudo snebu-client listbackups -n bosshost1 -d 1608761077 '*BudgetProposal*'

/home/bigboss/BudgetProposal2021.doc
----
----
$ sudo snebu-client restore -n bosshost1 -d 1608761077 -C /tmp \
    --graft /home/bigboss/=bigboss-restored

 bigboss-restored/BudgetProposal2021.doc
----

The first command gives a list of all hosts that have been backed up.  With the "-v" flag, it will also give all backup sets that are part of each backed up host.  Backup sets are identified by a serial number, which is the time/date that the backup was created, represented in Unix time_t format (i.e., the number of seconds since Jan 1, 1970).

The second command will list the files that are part of the host and backup set, restricting the output to the given file specification.

In the third command, a restore of this backup set is initiated.  The client changes to the "/tmp" directory, so everything restored is relative to this directory (or specify `-C /` to restore to the original location).  The `--graft` parameter is specified to re-write part of the file path -- in this case it replaces the directory "/home/bigboss/" with "bigboss-restored".  Putting it together the final path file that gets restored is in `/tmp/bigobss-restored/BudgetProposal2021.doc`.

Notice that the backup above is a "daily" backup -- this is the retention schedule that this backup set is assigned to.  By default, backups ran on Sunday through Friaday are `daily` backups, Saturday is a `weekly` backup, and the first of the month is a `monthly` backup.

==== Remote backups
If snebu is installed in a remote backup server called `bkupsvr1`, and you have the snebu-client script on a local host, you can add the parameters `--backup-server bkupsvr1` and `--backup-user svc-bosshost1` to the above commands.  Make sure to create the service user account `svc-bosshost1` on the remote host (or whichever user account name specified by your organizations practices), along with adding the account to the snebu group.  Set up ssh key based authentication for unattended backups, and then create the appropriate permissions for this service user on the remote backup server:

    admin@bkupsvr1:~$ sudo -u snebu snebu permissions --add --command '*' \
        --name 'bosshost1' --user svc-bosshost1

Now you can back up to this host:

    root@booshost1:~$ sudo snebu-client backup --backup-server bkupsvr1 --backup-user svc-bosshost1

Note, you may wish to grant more granular permissions such as "backup", "listbackups" and "restore" in the above `snebu permissions` command.  This would prevent the client from deleting backups on the backup server if it were to become compromised.  See the `snebu-permissions` man page for detailed command usage.

If you want more protection, you can reverse the process and have the remote backup server "pull" a backup from the client:

    snebu@bkupsvr1:~$ snebu-client backup --remote-client bosshost1 \
        --remote-user root --sudo svs-backup

This will access bosshost1 as the service user `svs-backup`, then sudo to `root` to pull the data.  Make sure to set up ssh key authentication between `snebu@bkupsvr1` and `svs-backup@bosshost1`.  If you leave off the `--sudo` flag, then the user `root` will be directly accessed via ssh (requiring ssh key authorization to `root@bosshost1`)


==== Expiring old backups

Run the following on the backup server to expire old backups
----
$ sudo snebu expire -a 14 -r daily
$ sudo snebu exipre -a 42 -r weekly
$ sudo snebu expire -a 365 -r monthly
$ sudo snebu purge
----

This expires all daily backups older than 2 weeks, weekly backups older than 6 weeks, and monthly backups older than a year.  Expiring a backup only removes the metadata, and takes a short amount of time.  A `purge` permanently remove data from the `vault`, and can take a bit longer (depending on the number of files that need to be removed).

In the above example, the commands were run under the user ID `snebu`, which owns the repository and has all permissions.  Again, you can grant a specific user permission to run the expire and purge commands to limit the need to access the main user account (see _snebu-permissions(1)_ documentation).

==== Encryption
Snebu supports client-side public key encryption.  This requires the program `tarcrypt` to be installed on the client.  On the client, run the command `tarcrypt genkey -f outputfile`, and make sure it has appropriate permissions and ownership

    $ sudo tarcrypt genkey -f /etc/snebu-backup.key
    $ sudo chown root:root /etc/snebu-backup.key
    $ sudo chmod 600 /etc/snebu-backup.key

You will be prompted for a passphrase to protect the private key stored in the `.key` file.  Then, on any of the backup command variations, add the parameter `--encryption-key /etc/snebu-backup.key`:

    sudo snebu-client backup --backup-server bkupsvr1 --backup-user svc-bosshost1 \
        --encryption-key /etc/snebu-backup.key

Note, you can repeate the `--encryption-key` parameter to encrypt with multiple keys -- in this case, the passphrase for any one of the keys can be used to decode the backup upon restoring.

When restoring an encrypted backup, specify `snebu-client restore --decrypt` along with the other parameters as appropriate.  No key file is specified, as all key data is securely stored with the backup.  You will be prompted for the private key passphrase for one of the keys when restoring.
