=== snebu-newbackup(1) - Submits manifest for a new backup


----
snebu newbackup -n backupname -d datestamp -r schedule
----

==== Description

The "newbackup" command creates a new backup set, by consuming a
tab-delimited list of file names (along with associated meta data) to
include in the backup.  It then compares this list to the backup
catalog database to determine which files are new, and which ones are
already contained on the backup media.  A list of new / changed files
is returned (the snapshot manifest), which can then be passed along to
"tar" to generate the input for the "submitfiles" subcommand.

==== Options


*-n*, *--name* _backupname_::
Name of the backup.  Usually set to the server
name that you are backing up.

*-d*, *--date* _datestamp_::
Date stamp for this backup set.  The format is in
time_t format, sames as the output of the "date
+%s" command.

*-r*, *--retention* _schedule_::
Retention schedule for this backup set.  Typical
values are "daily", "weekly", "monthly", "yearly".

*-T*, *--files-from* _FILE_::
Read list of filenames (with meta data) to backup
from the named file, instead of standard input.

*--null*::
Inbound backup manifest (*-T*, or standard input)
is null terminated

*--not-null*::
Inbound backup manifest (*-T*, or standard input)
is newline terminated

*--null-output*::
Generate snapshot manifest with null-terminated lines.

*--not-null-output*::
Generate snapshot with newline-terminated lines.

*-f*, *--force-full*::
Force a full backup

*--graft* _/path/name/_*=*_/new/name/_::
Re-write path names beginning with "_/path/name/_"
to "_/new/name/_"

*-v*::
Turn on verbose output.

[discrete]
==== Input Manifest format

The input manifest contains a list of files to include in this backup set.
The format is a delimited list of file names and file metadata, with the following fields:
.BP


*1 - FType*::
Values are one of "f", "d", "l", "c", "b"

*2 - Mode*::
File mode in octal

*3 - Device*::
Device number of file system

*4 - Inode*::
Inode number of file

*5 - UName*::
User name

*6 - UID*::
User ID number

*7 - GName*::
User's Group Name

*8 - GID*::
User's Group Number

*9 - Size*::
File size in bytes

*10 - Hash*::
File Hash (future use, set to "0")

*11 - CTime*::
File Inode's last change time

*12 - MTime*::
File Content's last modififed time

*13 - Path*::
Full file path

*14 - LTarget*::
Link target

Field 14 (Link Target) is only present if the file type is "l" (symbolic link).

The fields are tab-delimited.  If the "--null" option is specified, then each line is null terminated, with an additional null character delimiting fields 13 and 14.  Otherwise if "--not-null" is specified, fields 13 and 14 are tab delimited, and the path names must have special characters escaped.

The input manifest can be created with the GNU _find_ command, with the following print formatting specification (suitable for the "--null" flag):

.EX
find [ parameters ] \( -type f -o -type d \ .br
    -printf "%y\t%#m\t%D\t%i\t%u\t%U\t%g\t%G\t%s\t0\t%C@\t%T@\t%p\0" .br
    -o -type l -printf "%y\t%#m\t%D\t%i\t%u\t%U\t%g\t%G\t%s\t0\t%C@\t%T@\t%p\0%l\0"
.EE

[discrete]
==== Returned Snapshot manifest output

The manifest returned is either a null-delimited list of files (if "--null-output" is specified),
or a newline-delimited list of files with special characters escaped (if "--not-null-output is specified).
This is the list of files that are required to complete the snapshot (any file that hasn't changed from previous backups will be referenced from the backup server).  This list is suitable for passing into the _tar_ command.

==== See Also

*snebu*(1),
*snebu-submitfiles*(1),
*snebu-restore*(1),
*snebu-listbackups*(1),
*snebu-expire*(1),
*snebu-purge*(1),
*snebu-permissions*(1),
*snebu-client*(1)
