=== tarcrypt(1) - Compresses and encrypts file data in TAR files


----
tarcrypt encrypt -k keyfile
 tarcrypt decrypt
 tarcrypt genkey -f keyfile -c comment
----

==== Description

The _tarcrypt_ command acts as a filter for the _tar_ command.
In encryption mode, it will compress and encrypt the data portion of TAR files
while leaving header metadata intact.  This allows the TAR file to be sent to
a backup system that expects the Unix TAR format as input.

The key file that is generated by the _genkey_ function contains an encrypted
(passphrase protected) RSA private key, public key, and HMAC key used for verification.
The encrypted private key, public key, and a hash of the HMAC key are stored in
the TAR file's global header.

Each individual file is encrypted with a random AES-256 key, which is in turn encrypted
using the RSA public key.  The file contents is also signed using the HMAC key,
and the signature for the file is attached to the file header.

During a decrypt operation, the user is prompted for the passphrase protecting the private key,
which is used to decrypt the AES key stored with each file.
The passphrase, along with the public key hash, are used to re-create the secret HMAC key
in order to validate each file contents as it is begin decrypted.

==== Options


*encrypt*::
Reads the tar command output on standard input, outputting an encrypted tar file.
    *Parameters*:
 ** *-k*, *--keyfile* _keyfilename_ +
Specifies the key file (generated by the _genkey_ subcommand)

Multiple key files may be specified by repeating this parameter.


*decrypt*::
Reads an encrypted tar file on standard input, prompts for the passphrase,
decrypts and verifies contents outputting a standard tar file.

*genkey*::
Generates a key file used by the _encrypt_ function.
    *Parameters:*
 ** *-f*, *--filename* _keyfilename_ +
Specifies the filename to write the keyfile out to.
 ** [ *-c*, *--comment* "_comment text_" ] +
Specifies a comment to include in the keyfile.

==== Security

Public Key cryptography splits up a key into two parts -- an encryption (public) key, and a decryption (private) key.
The public key isn't considered sensitive -- it is designed so that one party can send encrypted data to another party,
by using the other party's public key.  The private key, however, needs to be kept confidential by the receiving party.
Typically the private key is stored encrypted with a symmetric algorithm (one where the same password is used to both encrypt
and decrypt the data) to provide additional security.

In the case of tarcrypt, the sending and receiving party is the same entity,
using a third party (the backup server) to store the encrypted data.
If the backup is needed, chances are that the keyfile used to encrypt the backup is lost also.
Therefore, both the public key (for reference), and an encrypted copy of the private key are stored
in the generated encrypted tar file's global header.

For the purpose of file confidentiality the keyfile isn't considered sensitive,
as the private key used to decrypt the data is stored in encrypted form.
However, the keyfile also contains a secret HMAC key used to authenticate the contents of the encrypted
tar file.  Therefore if authenticity is needed, then the keyfile must be kept confidential
(i.e., stored with appropriate file system permissions to be accessed only by the backup process).

==== Notes

The tarcrypt file format is an extension of the PAX TAR format, with custom values in the PAX header.
If used in conjunction with a backup tool which expects the TAR format as input,
then the backup tool may need some modifications in order to handle the extensions.
If the tool stores the tar file intact, and if it doesn't choke on the custom header fields,
then no modifications should be necessary.  However if the backup system parses out the TAR file format
(i.e., it if uses it as a serialization format), then it would need to be modified to store the encrypted
header info along with the rest of the metadata, and re-generate the appropriate global and individual
file headers.
